# Generated by Django 5.2.3 on 2025-12-07 11:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kirks', '0003_remove_news_description_news_content_news_slug_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='news',
            name='image2',
            field=models.ImageField(blank=True, null=True, upload_to='news/'),
        ),
        migrations.AddField(
            model_name='news',
            name='image3',
            field=models.ImageField(blank=True, null=True, upload_to='news/'),
        ),
    ]
