# Generated by Django 5.2.3 on 2025-12-07 11:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kirks', '0004_news_image2_news_image3'),
    ]

    operations = [
        migrations.AddField(
            model_name='news',
            name='image4',
            field=models.ImageField(blank=True, null=True, upload_to='news/'),
        ),
        migrations.AddField(
            model_name='news',
            name='image5',
            field=models.ImageField(blank=True, null=True, upload_to='news/'),
        ),
        migrations.AddField(
            model_name='news',
            name='image6',
            field=models.ImageField(blank=True, null=True, upload_to='news/'),
        ),
        migrations.AddField(
            model_name='news',
            name='image7',
            field=models.ImageField(blank=True, null=True, upload_to='news/'),
        ),
    ]
